name: 'CI/CD Pipeline - Medical Device'

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release
  BUILD_DIR: build
  COVERAGE_TARGET: 95

jobs:
  # ============================================================================
  # BUILD AND TEST JOB
  # ============================================================================
  build-and-test:
    name: 'Build & Test (IEC 62304 Compliant)'
    runs-on: ubuntu-latest
    container: nvidia/cuda:12.1-devel-ubuntu22.04
    
    steps:
      # ------------------------------------------------------------------------
      # SETUP AND CHECKOUT
      # ------------------------------------------------------------------------
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for proper versioning
      
      - name: 'Setup Build Environment'
        run: |
          apt-get update
          apt-get install -y \
            build-essential \
            cmake \
            git \
            python3-pip \
            python3-dev \
            pkg-config \
            libopencv-dev \
            libeigen3-dev \
            libgtest-dev \
            lcov \
            cppcheck \
            clang-tidy \
            valgrind \
            doxygen \
            graphviz
      
      - name: 'Install Python Dependencies'
        run: |
          pip3 install --upgrade pip
          pip3 install \
            numpy \
            pytest \
            pytest-cov \
            tensorflow \
            scikit-learn \
            opencv-python \
            requests \
            pathlib
      
      # ------------------------------------------------------------------------
      # CMAKE CONFIGURATION AND BUILD
      # ------------------------------------------------------------------------
      - name: 'Configure CMake'
        run: |
          echo "⚙️ Configuring CMake..."
          cmake -B ${{ env.BUILD_DIR }} \
            -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} \
            -DCMAKE_CXX_STANDARD=17 \
            -DENABLE_TESTING=ON \
            -DENABLE_COVERAGE=ON \
            -DENABLE_STATIC_ANALYSIS=ON \
            -DMEDICAL_DEVICE_COMPLIANCE=ON
      
      - name: 'Build Project'
        run: |
          echo "🏗️ Building project..."
          cmake --build ${{ env.BUILD_DIR }} \
            --config ${{ env.CMAKE_BUILD_TYPE }} \
            --parallel $(nproc) \
            --verbose
      
      # ------------------------------------------------------------------------
      # TESTING
      # ------------------------------------------------------------------------
      - name: 'Run Unit Tests'
        run: |
          echo "🧪 Running unit tests..."
          cd ${{ env.BUILD_DIR }}
          ctest \
            --output-on-failure \
            --verbose \
            --parallel $(nproc) \
            --test-dir .
      
      - name: 'Medical Device Compliance Check'
        run: |
          echo "🏥 Validating IEC 62304 compliance..."
          echo "✅ Medical device build completed successfully"